package com.cloud.framework.utils.exceptions;

/**
 * 断言异常
 * */
public class AsserException extends RuntimeException{
    public AsserException(String message) {
        super(message);
    }
}
